# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calendar(object):
    def setupUi(self, Dialog, report_case_win):
        Dialog.setObjectName("Dialog")
        Dialog.resize(403, 271)
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        Dialog.setModal(True)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(-20, -60, 471, 461))
        self.frame_2.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame_2)
        self.calendarWidget.setGeometry(QtCore.QRect(20, 60, 411, 271))
        self.calendarWidget.setStyleSheet("background-color: rgb(185, 185, 185);")
        self.calendarWidget.setObjectName("calendarWidget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        widget = QtWidgets.QCalendarWidget
        widget.mouseDoubleClickEvent = self.select_date(report_case_win, Dialog)

        self.calendarWidget.mouseDoubleClickEvent

    def select_date(self, report_case_win, Dialog):
        date = self.calendarWidget.selectedDate()
        report_case_win.set_date(str(date.toPyDate()))
        Dialog.close()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
