# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import login_win

class Ui_Dialog(object):
    def setupUi(self, Dialog, ClientMultiSocket):
        Dialog.setObjectName("Dialog")
        Dialog.resize(853, 709)
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(670, 220, 141, 51))
        self.pushButton.setStyleSheet("background-color: rgb(14, 154, 175);\n"
"color: rgb(255,255,255);\n"
"font-size: 16pt\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 280, 451, 421))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("xray1.png"))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(300, 20, 211, 111))
        self.label_2.setStyleSheet("color: rgb(14, 154, 175);\n"
"font-size: 42pt ")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(270, 120, 351, 31))
        self.label_6.setStyleSheet("color: rgb(0, 209, 255);\n"
"font-size: 20pt \n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(470, 300, 311, 291))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("pic.png"))
        self.label_7.setObjectName("label_7")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(660, 130, 141, 91))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("books3.png"))
        self.label_12.setObjectName("label_12")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(330, 170, 151, 61))
        self.pushButton_5.setStyleSheet("background-color: rgb(54, 54, 54);\n"
"color: rgb(255,255,255);\n"
"font-size: 14pt\n"
"")
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 170, 151, 61))
        self.pushButton_6.setStyleSheet("background-color: rgb(54, 54, 54);\n"
"color: rgb(255,255,255);\n"
"font-size: 14pt\n"
"")
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(180, 170, 151, 61))
        self.pushButton_7.setStyleSheet("background-color: rgb(54, 54, 54);\n"
"color: rgb(255,255,255);\n"
"font-size: 14pt\n"
"")
        self.pushButton_7.setDefault(False)
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(520, 30, 91, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo1.png"))
        self.label.setObjectName("label")
        self.label_2.raise_()
        self.label_6.raise_()
        self.label_4.raise_()
        self.label_12.raise_()
        self.pushButton.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.label_7.raise_()
        self.label.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.pushButton.clicked.connect(lambda: self.open_login_win(ClientMultiSocket, Dialog))

    def open_login_win(self, ClientMultiSocket, Dialog):
        Dialog.close()
        is_connected = False
        if not is_connected:
            self.dialog = QtWidgets.QDialog()
            self.ui = login_win.Ui_LoginD()
            self.ui.setupUi(self.dialog, ClientMultiSocket)
            self.dialog.show()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Login System"))
        self.label_2.setText(_translate("Dialog", "DeTECh"))
        self.label_6.setText(_translate("Dialog", "Best way to detect disesases"))
        self.pushButton_5.setText(_translate("Dialog", "user history"))
        self.pushButton_6.setText(_translate("Dialog", "about DeTECh"))
        self.pushButton_7.setText(_translate("Dialog", "X-rays detection"))
