# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report_case.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sendCurl


class Ui_Report_case(object):
    def setupUi(self, Dialog, client, main_win, doctor_id):
        Dialog.setObjectName("Dialog")
        Dialog.resize(529, 603)
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 270, 121, 21))
        self.label_7.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 12pt")
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 210, 111, 21))
        self.label_9.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 12pt")
        self.label_9.setObjectName("label_9")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(20, 230, 391, 31))
        self.lineEdit_5.setAutoFillBackground(False)
        self.lineEdit_5.setStyleSheet("background-color: rgb(197,197,197);\n"
"color: rgb(42, 42, 42);\n"
"font-size: 12pt")
        self.lineEdit_5.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.lineEdit_5.setText("")
        self.lineEdit_5.setPlaceholderText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 331, 71))
        self.label_3.setStyleSheet("background-color: rgb(54,54,54);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 28pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")

        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 331, 71))
        self.label_11.setStyleSheet("background-color: rgb(54,54,54);\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "font: 75 28pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.label_3.raise_()
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 111, 21))
        self.label_5.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 12pt")
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 330, 181, 21))
        self.label_8.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 12pt")
        self.label_8.setObjectName("label_8")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 170, 391, 31))
        self.lineEdit_3.setAutoFillBackground(False)
        self.lineEdit_3.setStyleSheet("background-color: rgb(197,197,197);\n"
"color: rgb(42, 42, 42);\n"
"font-size: 12pt\n"
"")
        self.lineEdit_3.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 110, 391, 31))
        self.lineEdit_4.setAutoFillBackground(False)
        self.lineEdit_4.setStyleSheet("background-color: rgb(197,197,197);\n"
"color: rgb(42, 42, 42);\n"
"font-size: 12pt\n"
"")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setPlaceholderText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 12pt")
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(20, 350, 491, 111))
        self.textEdit.setStyleSheet("background-color: rgb(197,197,197);\n"
"color: rgb(42, 42, 42);\n"
"font-size: 12pt")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 540, 171, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(14, 154, 175);\n"
"color: rgb(255,255,255);\n"
"font-size: 18pt\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(20, 470, 301, 21))
        self.label_10.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 12pt")
        self.label_10.setObjectName("label_10")

        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(20, 470, 301, 21))
        self.label_12.setStyleSheet("color: rgb(255,255,255);\n"
                                    "font-size: 12pt")
        self.label_12.setObjectName("label_12")
        self.dateEdit = QtWidgets.QDateEdit(Dialog, calendarPopup=True)
        self.dateEdit.setGeometry(QtCore.QRect(20, 291, 171, 31))
        self.dateEdit.setStyleSheet("background-color: rgb(197,197,197);\n"
"color: rgb(42, 42, 42);\n"
"font-size: 12pt")
        self.dateEdit.setObjectName("dateEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(20, 490, 401, 31))
        self.pushButton.setStyleSheet("background-color: rgb(197,197,197);\n"
"color: rgb(42, 42, 42);\n"
"font-size: 12pt;\n"
"border-color: rgb(255, 255, 255);\n"
"text-align:left")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.dateEdit.setDisplayFormat("dd-MM-yyyy")
        self.dateEdit.setDateTime(QtCore.QDateTime.currentDateTime())

        self.pushButton.clicked.connect(lambda: self.select_photo(main_win))
        self.pushButton_2.clicked.connect(lambda: self.report(Dialog, client, main_win, doctor_id))

    def report(self, Dialog, client, main_win, doctor_id):
        full_name = self.lineEdit_4.text()
        ID = self.lineEdit_3.text()
        email = self.lineEdit_5.text()
        date = self.dateEdit.date()
        date = str(str(date.toPyDate()))
        case_description = self.textEdit.toPlainText()
        photo_path = self.pushButton.text()
        chance = ''
        if photo_path != '':
            chance = sendCurl.send_curl(photo_path)
        client.send_patient(full_name, ID, email, date, case_description, chance, doctor_id)
        main_win.clear_table()
        main_win.fill_table(client)
        Dialog.close()
    def select_photo(self, main_win):
        _translate = QtCore.QCoreApplication.translate
        photo_path = main_win.get_file_name()
        self.pushButton.setText(_translate("Dialog", photo_path))

    def turn_into_show_patient_mode(self, client, patient_id):
        self.label_11.raise_()

        self.lineEdit_4.setEnabled(False)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_5.setEnabled(False)
        self.dateEdit.setEnabled(False)
        self.textEdit.setEnabled(False)

        if self.pushButton.text() != '':
            self.pushButton.setEnabled(False)
        patient = client.get_specific_patient(patient_id)
        spllited_patient = patient.split(',')

        _translate = QtCore.QCoreApplication.translate

        self.lineEdit_4.setText(_translate("Dialog", spllited_patient[0]))
        self.lineEdit_3.setText(_translate("Dialog", spllited_patient[1]))
        self.lineEdit_5.setText(_translate("Dialog", spllited_patient[2]))
        spllited_date = spllited_patient[3].split('-')
        str_date = spllited_date[2] + spllited_date[1] +spllited_date[0]
        date = QtCore.QDate.fromString(str_date, 'ddMMyyyy')
        print(type(date))
        self.dateEdit.setDate(date)
        self.textEdit.setText(_translate("Dialog", spllited_patient[4]))
        if len(spllited_patient) > 6:
            self.label_10.setText(_translate("Dialog", "X-ray photo was already detected:"))
            self.pushButton.setEnabled()
            self.pushButton.setText(_translate("Dialog", spllited_patient[6]))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_7.setText(_translate("Dialog", "Last visit date:"))
        self.label_9.setText(_translate("Dialog", "E-mail:"))
        self.label_3.setText(_translate("Dialog", "Add new patient"))
        self.label_11.setText(_translate("Dialog", "Patient's details"))
        self.label_5.setText(_translate("Dialog", "ID:"))
        self.label_8.setText(_translate("Dialog", "Description of the case:"))
        self.label_4.setText(_translate("Dialog", "Full name:"))
        self.pushButton_2.setText(_translate("Dialog", "Submit"))
        self.label_10.setText(_translate("Dialog", "Add X-ray photo for detection (Optional):"))
        self.label_12.setText(_translate("Dialog", "Detection was already done"))

