# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_FileD(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(334, 388)
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 40, 281, 111))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 28pt ")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 160, 121, 51))
        self.pushButton_2.setStyleSheet("background-color: rgb(14, 154, 175);\n"
"color: rgb(255,255,255);\n"
"font-size: 14pt\n"
"")
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Please select file:"))
        self.pushButton_2.setText(_translate("Dialog", "Select file"))

        self.pushButton_2.clicked.connect(self.clicked)
    def clicked(self):
        #fname = QFileDialog.getOpenFileName(self,"Open File", "", "All Files (*);;Python Files (*.py)")
        #Dialog.destroy()
        response = self.getFileName()
        print(response)

    def getFileName(self):

        file_filter = 'Data File (*.py)'
        response = QFileDialog.getOpenFileName(
            caption='Select a data file',
            directory=os.getcwd(),
            filter=file_filter,
            initialFilter='Python File (*.py)'
        )
        print(response)
        return response[0]

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_FileD()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

def start():
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_FileD()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())